name: coverage

on:
  push:
    branches:
      - cypress
  # TODO: re-enable when https://github.com/cypress-io/cypress/issues/6053 is fixed
  # pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v1

    - name: Install npm dependencies
      run: yarn install

    - name: Build
      run: yarn build

    - name: Prepare src folder for generating coverage report
      run: yarn nyc:instrument

    - name: Run Cypress tests ang generate coverage report
      run: yarn cy:run:headless

    - name: Test & publish code coverage to codeclimate.com
      uses: paambaati/codeclimate-action@v2.4.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: ls -la coverage
